export const environment = {
    apiToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwb3NpdGlvbklkIjoiYTVjNjU3NDktMTZkOC00ZTUxLWIxZTYtY2M2MjNiMWJjNmRkIiwicHJvamVjdElkIjoiOTYyYTcwN2UtNGQyYy00MjIxLWI1ZjctMmEwYjgxM2JkYTkyIiwiZnVsbE5hbWUiOiJOb8OpIExhcmEiLCJlbWFpbCI6Im5vZV9sYXJhOTlAb3V0bG9vay5jb20iLCJpYXQiOjE3MjUwNTQ5NjB9.H28arkZtuUeoFTc3ttLKarX0v2wj6OD5lvDZvfL7HhE',
    apiBase: 'https://syn-api-prod.herokuapp.com/graphql'
};